services:
  dbResource:
    image: postgres
    environment:
      POSTGRES_DB: mp3db
      POSTGRES_USER: mp3
      POSTGRES_PASSWORD: mp3
    volumes:
      - data-resource:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  dbMeta:
    image: postgres
    environment:
      POSTGRES_DB: mp3Metadb
      POSTGRES_USER: mp3meta
      POSTGRES_PASSWORD: mp3meta
    volumes:
      - data-meta:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    volumes:
      - data-minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniomp3
      MINIO_ROOT_PASSWORD: miniomp3
    command: server /data --console-address ":9001"

volumes:
  data-resource:
  data-meta:
  data-minio: